//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopVirtual.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string EMail { get; set; }
        public string Descricao { get; set; }
        public int ID_Produto { get; set; }
        public int Nota { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
